use_frameworks!
inhibit_all_warnings!

project 'SwiftDataStructures.xcodeproj'

target 'SwiftDataStructures' do
  platform :ios, '8.0'
  pod 'SwiftLint'
end

target 'SwiftDataStructuresTests' do
  platform :ios, '8.0'
  pod 'SwiftLint'
end
